server:
  context-path: /manager
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://112.74.102.9:3306/succulent_man
    username: root
    password: root
    driver-class-name:  com.mysql.jdbc.Driver
  application:
    name: succulentMan
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    favicon:
      enabled: false
  aop:
    proxy-target-class: true
  freemarker:
    template-loader-path: ["classpath:/templates/", "classpath:/castemplates/"]

#pagehelper
pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    use-column-label: true
    auto-mapping-behavior: full
    default-statement-timeout: 2000
    map-underscore-to-camel-case: true
  mapper-locations:
    classpath:mapper/*.xml